server:
  port: 8081
spring:
  application:
    name: hmdp
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${hmdp.datasource.host}:${hmdp.datasource.port}/${hmdp.datasourse.database}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ${hmdp.datasource.username}
    password: ${hmdp.datasource.password}
  redis:
    host: 47.113.187.224
    port: 6379
    password: redis
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  profiles:
    active: dev
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug
#    jwt过期时间为1天
jwt:
  time: 86400000
# jwt的签名=
  secretKey: ElySia
